id: D1DCCD9C0
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-11-12T09:35:08+00:00'
last_modified: '2022-05-26T10:32:40.046690+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    '5193':
      image_group_id: I1PD95867
      title: འཕགས་པ་སྤྱན་རས་གཟིགས་འཇིག་རྟེན་དབང་ཕྱུག་སྒྲུབ་པའི་ཐབས།
      total_pages: 1409
      order: 22
      base_file: 5193.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
