id: 051d3d16ca88452f9a649cf56ed92a36
initial_creation_type: ocr
source_metadata:
  volumes:
    5eec784e576d46d290aa13b790dbedb4:
      base_file: v022.txt
      image_group_id: I1PD95867
      title: ''
      total_pages: 1409
      volume_number: 22
